### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by Sleepybear66** [GuangtaoLyu/FETNet#6]
您好，在您提到的对于数据集的描述中，数据集应该包含五个注释，It provides five types annotations, text removed images (b), pixel-level text masks (c), character instance segmentation labels, category labels and character-level bounding box labels(d). The word-level scene text regions can be calculated simply Implicitly from those labels.可是在我拿到数据集并顺利解压后，为什么在文件夹中只有原图和label图片，想向您请教一下是否在哪里出现了问题。
![image](https://github.com/user-attachments/assets/e672d012-158c-422e-8298-6e81cd987230)

**Comment by GuangtaoLyu** [comment]
Due to some copyright issues, we did not provide other more detailed annotations. Similar to SCUT-Syn, you can obtain different regions by subtracting the image from the label, and then apply simple digital image processing techniques such as binarization and dilation to obtain the mask. Furthermore, you can calculate the bounding box by finding the enclosing rectangle.
